# Generated by Django 2.2.28 on 2023-03-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_auto_20230323_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('show', 'Show'), ('song', 'Song')], max_length=50),
        ),
    ]
