# Generated by Django 2.2.28 on 2023-03-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20230323_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie'), ('Show', 'Show'), ('Song', 'Song')], max_length=50),
        ),
    ]
